name: Build and Push Docker Image to GAR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (default: latest)"
        required: false
        default: "latest"
        type: string
      registry_region:
        description: "Google Artifact Registry region"
        required: false
        default: "us-central1"
        type: string

env:
  REGISTRY: ${{ secrets.GAR_REGISTRY }}
  IMAGE_NAME: nova-discord-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker ${{ inputs.registry_region }}-docker.pkg.dev

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ inputs.image_tag }},enable={{is_default}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image info
        run: |
          echo "Successfully built and pushed image:"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Image: ${{ env.IMAGE_NAME }}"
